#include "../../src/math/vec.h"
#include "../../src/math/rect.h"
#include "../../src/math/bound.h"
#include "../../src/math/color.h"
#include "../../src/math/frustum.h"
#include "../../src/math/transform.h"
#include "../../src/math/attenuation.h"
